objs:
    ec846432f3ebedf0a6f32a8797e3b9e9:
      class_id: 0
      cluster_id: c0
      obj_xml_file: cups/ec846432f3ebedf0a6f32a8797e3b9e9.xml
      scale: 1.5
    bed9f618bef8d3e9f6d436d018e2b50f:
      class_id: 1
      cluster_id: c0
      obj_xml_file: bowls/bed9f618bef8d3e9f6d436d018e2b50f.xml
      scale: 2.0
    1c9f9e25c654cbca3c71bf3f4dd78475:
      class_id: 0
      obj_xml_file: cups/1c9f9e25c654cbca3c71bf3f4dd78475.xml
      scale: 1.5
    2a1e9b5c0cead676b8183a4a81361b94:
      class_id: 1
      obj_xml_file: bowls/2a1e9b5c0cead676b8183a4a81361b94.xml
      scale: 2.0
    524eb99c8d45eb01664b3b9b23ddfcbc:
      class_id: 1
      obj_xml_file: bowls/524eb99c8d45eb01664b3b9b23ddfcbc.xml
      scale: 2.0
    1d18255a04d22794e521eeb8bb14c5b3:
      class_id: 0
      obj_xml_file: cups/1d18255a04d22794e521eeb8bb14c5b3.xml
      scale: 1.5
    159e56c18906830278d8f8c02c47cde0:
      class_id: 0
      obj_xml_file: cups/159e56c18906830278d8f8c02c47cde0.xml
      scale: 1.2
    403fb4eb4fc6235adf0c7dbe7f8f4c8e:
      class_id: 0
      obj_xml_file: cups/403fb4eb4fc6235adf0c7dbe7f8f4c8e.xml
      scale: 1.5
    454fa7fd637177cf2bea4b6e7618432:
      class_id: 1
      obj_xml_file: bowls/454fa7fd637177cf2bea4b6e7618432.xml
      scale: 2.0
    414772162ef70ec29109ad7f9c200d62:
      class_id: 0
      obj_xml_file: cups/414772162ef70ec29109ad7f9c200d62.xml
      scale: 1.5
    hammer4:
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/hammer4.xml'
       scale: 1.0
    spray:
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/spray.xml'
       scale: 1.0
    bottle:
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/bottle.xml'
       scale: 1.0
    hammer:
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/hammer.xml'
       scale: 1.0
    nail2:
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/nail2.xml'
       scale: 1.0